### PR TITLE
fix: added fixes for flutter 3.22

### PR DESCRIPTION
**Pull request by erickgon92**
Updated libraries and fixed all necessary lines where the deprecated elements where being used.

### CODE REVIEW

**Comment by bkozik** [comment]
@ali-thowfeek Bumping this, as our project depends on it as well

**Review by LeNeuner — APPROVED** [review]

**Comment by martinogarrizzo5** [comment]
I really need this fix too!

**Comment by thearaks** [comment]
I need this PR to be merged and released too! 🙏

**Review by iharoonamjad — APPROVED** [review]

**Review by ali-thowfeek — CHANGES_REQUESTED** [review]
@erickgon92 Thank you for the PR. Really appreciate the time you put in 😇. There are few things we need to get right before we can go ahead with this PR.

Font sizes reference:
https://github.com/flutter/flutter/blob/5dcb86f68f239346676ceb1ed1ea385bd215fba1/packages/flutter/lib/src/material/text_theme.dart

**Comment by erickgon92** [comment]
Thank you all for your time!! I will make the fixes and inform you. Cheers all!

**Comment by ali-thowfeek** [comment]
@erickgon92 I've already merged your PR. Made the necessary changes on top myself. So no more changes needed on your part. 

New version 5.0.0 released. Thank you once again.

**Pull request merged**
