### PR TITLE
Update xml and flutter_lints package

### PR DESCRIPTION
**Pull request by nayanbabariya95**

### CODE REVIEW

**Review by nohli — APPROVED** [review]

**Comment by sysmesh** [comment]
Can you please push these changes to a new formal version? 
Flutter 3 is not working with the plugin due to the XML version issue

**Comment by nayanbabariya95** [comment]
Package has updated to support flutter 3 in this PR

**Comment by sysmesh** [comment]
> Package has updated to support flutter 3 in this PR

Thanks! But when I put:
simple_html_css: ^3.0.1+1

in the pubspec of the project it still does not contain these changes. 
Can I force them in or do I need to wait for you to release 3.0.1+2 ?

**Comment by nayanbabariya95** [comment]
You need to wait until this PR will merge.
This change is not included in 3.0.1+1

**Comment by nayanbabariya95** [comment]
Are you a beginner in flutter?

**Comment by nohli** [comment]
@ali-thowfeek let's merge, update version/changelog and release a new version? 😊

We also need to update to sdk: '>=2.17.0 <3.0.0', because of the xml dependency, plus make our release a major (breaking) change, as it won't support older Flutter versions.
@nayanbabariya95 could you already include these changes in your PR (sdk, version, changelog)?

**Comment by nayanbabariya95** [comment]
Sorry, I haven't included changelog

**Comment by nohli** [comment]
> @nohli , I haven't included changelog

Yes.
Could you add them to this PR?

**Comment by nayanbabariya95** [comment]
Okay. Will add shortly

**Comment by nohli** [comment]
@nayanbabariya95, already merged your contribution. Thanks for opening the PR! 🙂

**Pull request merged**
